version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule: { interval: weekly }
    open-pull-requests-limit: 3
  - package-ecosystem: npm
    directory: /frontend
    schedule: { interval: weekly }
    open-pull-requests-limit: 3
    groups:
      frontend-toolchain:
        patterns: ['vue*', '@vue*', 'vite*', '@vitejs/*', 'typescript', 'naive-ui', 'unocss', '@elegant-router/*']
  - package-ecosystem: composer
    directory: /backend
    schedule: { interval: weekly }
    open-pull-requests-limit: 3
  - package-ecosystem: cargo
    directory: /frontend/src-tauri
    schedule: { interval: weekly }
    open-pull-requests-limit: 3
    groups:
      tauri:
        patterns: ['tauri*']
  - package-ecosystem: github-actions
    directory: /
    schedule: { interval: weekly }
