map $request_uri $backend_uri {
    ~^/proxy-default(/.*)$ $1;
    default $request_uri;
}

server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    location ~ ^/(api|up|proxy-default)(/|$) {
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME /app/backend/public/index.php;
        fastcgi_param SCRIPT_NAME /index.php;
        fastcgi_param REQUEST_URI $backend_uri;
        fastcgi_pass api:9000;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
